name: IstioSM
services:
  istio:
    type: IstioMesh
    model: ISTIO
    namespace: istio-system
    version: #filled dynamically
    settings:
      profile: demo
      global:
        imagePullSecrets: []
        istioNamespace: istio-system

        istiod:
          enableAnalysis: false

        configValidation: true
        externalIstiod: false
        remotePilotAddress: ""

      base:
        enableCRDTemplates: false
        # Validation webhook configuration url
        # For example: https://$remotePilotAddress:15017/validate
        validationURL: ""
        enableIstioConfigCRDs: true

      defaultRevision: "default"