name: IstioSM
services:
  istio:
    type: IstioMesh
    model: ISTIO
    namespace: istio-system
    version: #will be filled dynamically in workflow
    settings:
      profile: demo
      global:
        imagePullSecrets: []
        istioNamespace: istio-system

        istiod:
          enableAnalysis: false

        configValidation: true
        externalIstiod: false
        remotePilotAddress: ""

      base:
        enableCRDTemplates: false
        # Validation webhook configuration url
        # For example: https://$remotePilotAddress:15017/validate
        validationURL: ""
        enableIstioConfigCRDs: true

      defaultRevision: "default"
    traits:
      automaticSidecarInjection:
        namespaces:
          - default
  grafana:
    type: GrafanaIstioAddon
    model: ISTIO
    version:  #will be filled dynamically in workflow
    namespace: istio-system
    dependsOn:
      - istio
      - prometheus
  prometheus:
    type: PrometheusIstioAddon
    model: ISTIO
    version:  #will be filled dynamically in workflow
    namespace: istio-system
    dependsOn:
      - istio